kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "pca-manager"
  namespace: "istio-system"
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "pca-manager"
  namespace: "istio-system"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "pca-manager"
subjects:
- kind: ServiceAccount
  name: "pca-manager"
  namespace: "istio-system"