apiVersion: v1
kind: ServiceAccount
metadata:
  name: "pca-manager"
  namespace: "istio-system"
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.oidcRole }}
  {{- if .Values.extraAnnotations }}
   {{ toYaml .Values.extraAnnotations | nindent 4 }}
  {{- end }}